import "./globals.css";
import { Montserrat, Marcellus_SC } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });
const marcellus_SC = Marcellus_SC({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
